apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment      # Name of the deployment
  namespace: k8s-tutorial       # In which namespace it will be created
  labels:
    app: restapi-pod
spec:
  replicas: 3                   # How many pods will be created
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: restapi-pod          # Which Pods to manage
  template:
    metadata:
      labels:
        app: restapi-pod
    spec:
      containers:
      - name: restapi-container # Name of the container
        image: nginx:1.14.2

        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
