apiVersion: v1
kind: Service
metadata:
  name: restapi-service     # Name of the service
  namespace: k8s-tutorial   # In which namespace it will be created
spec:
  selector:
    app: pingapi-pod        # Which Pods will be targeted
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000           # Port used by the service
    targetPort: 80       # Target port in the Pod
